from rest_framework import serializers
from Predict.serializer.DatasetPredSerializer import DatasetPredSerializer
from Predict.serializer.DatasetTrainSerializer import DatasetTrainSerializer
from Predict.serializer.HistorialPredictSerializer import HistorialPredictSerializer