from rest_framework import serializers
from .serializer.HaciendaSerializer import HaciendaSerializers
from .serializer.LecturaSerializer import LecturaSerializers
from .serializer.LoteSerializer import LoteSerializers
from .serializer.ProyectoHaciendaSerializer import ProyectoHaciendaSerializer
from .serializer.UserSerializer import UserSerializer
from .serializer.ProyectoSerializer import ProyectoSerializers
from .serializer.PoligonoSerializer import PoligonoSerializers
from .serializer.GeoCoordenadasSerializer import GeoCoordenadasSerializers

