# Generated by Django 4.2.1 on 2023-11-26 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0028_lectura_fecharegistro_produccion'),
        ('Users', '0002_rename_usuarios_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='Id_Hacienda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.hacienda'),
        ),
    ]
