# Generated by Django 4.2.1 on 2023-05-18 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hacienda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Proyecto', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=40)),
                ('Id_Hacienda', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.hacienda')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Hacienda', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=40)),
                ('Variedad', models.CharField(max_length=20)),
                ('Hectareas', models.IntegerField()),
                ('Id_Proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.proyecto')),
            ],
        ),
    ]
