# Generated by Django 4.2.1 on 2023-05-18 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Estacion', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.RenameField(
            model_name='lote',
            old_name='Codigo_Hacienda',
            new_name='Codigo_Lote',
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Planta', models.CharField(max_length=10)),
                ('Nombre', models.CharField(max_length=40)),
                ('Id_Estacion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.estacion')),
            ],
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('E1', models.IntegerField(blank=True, default=0, null=True)),
                ('E2', models.IntegerField(blank=True, default=0, null=True)),
                ('E3', models.IntegerField(blank=True, default=0, null=True)),
                ('E4', models.IntegerField(blank=True, default=0, null=True)),
                ('E5', models.IntegerField(blank=True, default=0, null=True)),
                ('Monilla', models.IntegerField(blank=True, default=0, null=True)),
                ('Phythptora', models.IntegerField(blank=True, default=0, null=True)),
                ('Colletotrichum', models.IntegerField(blank=True, default=0, null=True)),
                ('Corynespora', models.IntegerField(blank=True, default=0, null=True)),
                ('Lasodiplodia', models.IntegerField(blank=True, default=0, null=True)),
                ('Cherelles', models.IntegerField(blank=True, default=0, null=True)),
                ('Insectos', models.IntegerField(blank=True, default=0, null=True)),
                ('Animales', models.IntegerField(blank=True, default=0, null=True)),
                ('Observacion', models.TextField(max_length=100)),
                ('Id_Planta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.planta')),
            ],
        ),
        migrations.AddField(
            model_name='estacion',
            name='Id_Lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote'),
        ),
    ]
