# Generated by Django 4.2.1 on 2023-05-22 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0003_alter_lote_hectareas_alter_lote_variedad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estacion',
            name='Codigo_Estacion',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='planta',
            name='Codigo_Planta',
            field=models.CharField(max_length=20),
        ),
    ]
