# Generated by Django 4.2.1 on 2023-05-22 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0004_alter_estacion_codigo_estacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='FechaVisita',
            field=models.DateField(null=True),
        ),
    ]
