# Generated by Django 4.2.1 on 2023-05-22 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0005_lectura_fechavisita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='Observacion',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
