# Generated by Django 4.2.1 on 2023-06-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0006_alter_lectura_observacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hacienda',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
