# Generated by Django 4.2.1 on 2023-07-15 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('Hacienda', '0008_customuser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomUser',
            new_name='Usuarios',
        ),
    ]
