# Generated by Django 4.2.1 on 2023-07-23 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0009_rename_customuser_usuarios'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeoCoordenadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('lng', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Poligono',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FillColor', models.CharField(max_length=7)),
                ('IdLote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote')),
            ],
        ),
        migrations.RemoveField(
            model_name='planta',
            name='Id_Estacion',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='Id_Planta',
        ),
        migrations.AddField(
            model_name='lectura',
            name='Id_Lote',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote'),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='Monilla',
            field=models.IntegerField(choices=[(1, 'Grado1'), (2, 'Grado2'), (3, 'Grado3'), (4, 'Grado4'), (5, 'Grado5')]),
        ),
        migrations.DeleteModel(
            name='Estacion',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.AddField(
            model_name='geocoordenadas',
            name='IdPoligono',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.poligono'),
        ),
    ]
