# Generated by Django 4.2.1 on 2023-07-23 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0010_geocoordenadas_poligono_remove_planta_id_estacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='Monilla',
            field=models.IntegerField(choices=[(1, 'Grado1'), (2, 'Grado2'), (3, 'Grado3'), (4, 'Grado4'), (5, 'Grado5')], max_length=10),
        ),
    ]
