# Generated by Django 4.2.1 on 2023-07-23 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0012_alter_lectura_monilla'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geocoordenadas',
            old_name='IdPoligono',
            new_name='Id_Poligono',
        ),
        migrations.RenameField(
            model_name='poligono',
            old_name='IdLote',
            new_name='Id_Lote',
        ),
        migrations.AddField(
            model_name='geocoordenadas',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='poligono',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
