# Generated by Django 4.2.1 on 2023-07-23 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0013_rename_idpoligono_geocoordenadas_id_poligono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocoordenadas',
            name='lat',
            field=models.DecimalField(decimal_places=16, max_digits=18),
        ),
        migrations.AlterField(
            model_name='geocoordenadas',
            name='lng',
            field=models.DecimalField(decimal_places=16, max_digits=19),
        ),
    ]
