# Generated by Django 4.2.1 on 2023-08-13 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0014_alter_geocoordenadas_lat_alter_geocoordenadas_lng'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuarios',
        ),
    ]
