# Generated by Django 4.2.1 on 2023-09-03 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0015_delete_usuarios'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lectura',
            old_name='Animales',
            new_name='GR1',
        ),
        migrations.RenameField(
            model_name='lectura',
            old_name='Colletotrichum',
            new_name='GR2',
        ),
        migrations.RenameField(
            model_name='lectura',
            old_name='Corynespora',
            new_name='GR3',
        ),
        migrations.RenameField(
            model_name='lectura',
            old_name='Insectos',
            new_name='GR4',
        ),
        migrations.RenameField(
            model_name='lectura',
            old_name='Lasodiplodia',
            new_name='GR5',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='Monilla',
        ),
        migrations.RemoveField(
            model_name='lectura',
            name='Phythptora',
        ),
    ]
