# Generated by Django 4.2.1 on 2023-09-09 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0016_rename_animales_lectura_gr1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='GUIDLectura',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='Usuario',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
