# Generated by Django 4.2.1 on 2023-09-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0017_lectura_guidlectura_lectura_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='geocoordenadas',
            name='Usuario',
            field=models.TextField(default='SYSTEM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hacienda',
            name='Usuario',
            field=models.TextField(default='SYSTEM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lectura',
            name='SyncId',
            field=models.TextField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='lote',
            name='Usuario',
            field=models.TextField(default='SYSTEM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='poligono',
            name='Usuario',
            field=models.TextField(default='SYSTEM', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='Usuario',
            field=models.TextField(default='SYSTEM', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lectura',
            name='Usuario',
            field=models.TextField(default='SYSTEM', max_length=100, null=True),
        ),
    ]
