# Generated by Django 4.2.1 on 2023-09-09 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0018_geocoordenadas_usuario_hacienda_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='Usuario',
            field=models.TextField(default='Admin', max_length=100, null=True),
        ),
    ]
