# Generated by Django 4.2.1 on 2023-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0019_alter_lectura_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geocoordenadas',
            name='Usuario',
            field=models.TextField(default='Admin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hacienda',
            name='Usuario',
            field=models.TextField(default='Admin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='lote',
            name='Usuario',
            field=models.TextField(default='Admin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='poligono',
            name='Usuario',
            field=models.TextField(default='Admin', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Usuario',
            field=models.TextField(default='Admin', max_length=100, null=True),
        ),
    ]
