# Generated by Django 4.2.1 on 2023-09-15 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0020_alter_geocoordenadas_usuario_alter_hacienda_usuario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='Id_Lote',
        ),
        migrations.CreateModel(
            name='Planta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Codigo_Planta', models.CharField(max_length=20)),
                ('Nombre', models.CharField(max_length=40)),
                ('Activo', models.BooleanField(default=True)),
                ('Id_Lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote')),
            ],
        ),
        migrations.AddField(
            model_name='lectura',
            name='Id_Planta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.planta'),
        ),
    ]
