# Generated by Django 4.2.1 on 2023-09-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0021_remove_lectura_id_lote_planta_lectura_id_planta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='FechaVisita',
            field=models.DateTimeField(null=True),
        ),
    ]
