# Generated by Django 4.2.1 on 2023-09-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0022_alter_lectura_fechavisita'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='Observacion',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
