# Generated by Django 4.2.1 on 2023-09-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0023_alter_lectura_observacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lectura',
            name='Id_Planta',
        ),
        migrations.AddField(
            model_name='lectura',
            name='Planta',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.planta'),
        ),
    ]
