# Generated by Django 4.2.1 on 2023-10-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0025_remove_lectura_planta_lectura_id_planta'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='Monilla',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
