# Generated by Django 4.2.1 on 2023-11-04 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0026_lectura_monilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='lectura',
            name='Total',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='planta',
            name='Circunferencia',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
