# Generated by Django 4.2.1 on 2023-11-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0028_lectura_fecharegistro_produccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lectura',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='produccion',
            name='FechaRegistro',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
