# Generated by Django 4.2.1 on 2023-11-30 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0030_alter_lote_hectareas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lote',
            name='Hectareas',
            field=models.DecimalField(decimal_places=3, max_digits=7, null=True),
        ),
    ]
