# Generated by Django 4.2.1 on 2023-11-30 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0031_alter_lote_hectareas'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='Densidad',
            field=models.IntegerField(null=True),
        ),
    ]
