# Generated by Django 4.2.1 on 2023-11-30 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0032_proyecto_densidad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produccion',
            name='Id_Lote',
        ),
        migrations.AddField(
            model_name='produccion',
            name='Id_Proyecto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.proyecto'),
            preserve_default=False,
        ),
    ]
