# Generated by Django 4.2.1 on 2023-12-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0033_remove_produccion_id_lote_produccion_id_proyecto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='Fecha',
            field=models.DateTimeField(),
        ),
    ]
