# Generated by Django 4.2.1 on 2023-12-03 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0034_alter_produccion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produccion',
            name='Fecha',
            field=models.DateField(),
        ),
    ]
