# Generated by Django 4.2.1 on 2023-12-08 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0035_alter_produccion_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='planta',
            name='Visible',
            field=models.BooleanField(default=True),
        ),
    ]
