# Generated by Django 4.2.1 on 2023-12-23 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0037_remove_produccion_id_proyecto_planta_lat_planta_lng_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planta',
            old_name='Visible',
            new_name='VisibleToStudent',
        ),
    ]
