# Generated by Django 4.2.1 on 2024-01-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0038_rename_visible_planta_visibletostudent'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='FechaSiembra',
            field=models.DateTimeField(null=True),
        ),
    ]
