# Generated by Django 4.2.1 on 2024-04-25 14:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0041_lote_num_plantas'),
    ]

    operations = [
        migrations.AddField(
            model_name='hacienda',
            name='FechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='lote',
            name='FechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='planta',
            name='FechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='FechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
