# Generated by Django 4.2.1 on 2024-02-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Hacienda', '0040_lote_edad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField(blank=True, default=0, null=True)),
                ('E1', models.IntegerField(blank=True, default=0, null=True)),
                ('E2', models.IntegerField(blank=True, default=0, null=True)),
                ('E3', models.IntegerField(blank=True, default=0, null=True)),
                ('E4', models.IntegerField(blank=True, default=0, null=True)),
                ('E5', models.IntegerField(blank=True, default=0, null=True)),
                ('grade_monilla', models.IntegerField(blank=True, default=0, null=True)),
                ('qq', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Evapotranspiration_Crop', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Nvdi', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Relat_Hum_Max_Temp', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Temp_Air_Max', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Temp_Air_Min', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Dew_Temp_Max', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Precipitacion', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Sunshine_Duration', models.DecimalField(decimal_places=3, max_digits=18)),
                ('Id_Lote', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote')),
            ],
        ),
    ]
