# Generated by Django 4.2.1 on 2024-04-06 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0041_lote_num_plantas'),
        ('Predict', '0005_alter_dataset_hectareas'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialPredict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupPrediction', models.UUIDField(editable=False)),
                ('Qq', models.DecimalField(decimal_places=4, max_digits=8)),
                ('Orden', models.IntegerField(default=1)),
                ('Fecha', models.DateField()),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Usuario', models.TextField(default='Admin', max_length=100, null=True)),
                ('Id_Lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Hacienda.lote')),
            ],
        ),
    ]
