# Generated by Django 4.2.1 on 2024-04-06 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0006_historialpredict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpredict',
            name='Qq',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
