# Generated by Django 4.2.1 on 2024-04-07 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Predict', '0007_alter_historialpredict_qq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialpredict',
            name='GroupPrediction',
            field=models.TextField(max_length=100),
        ),
    ]
