from Users.serializer.UserSerializer import UserSerializer 
from Users.serializer.GroupSerializer import GroupSerializer 
from Users.serializer.UserSerializer import PerfilSerializer 
from Users.serializer.AsignacionGrupoSerializer import AsignacionGrupoSerializer
from Users.serializer.PemisionsSerializer import PermisionsSerializer
