# Generated by Django 4.2.1 on 2023-09-10 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Viento_Velocidad', models.IntegerField(blank=True, default=0, null=True)),
                ('Fecha', models.DateField(blank=True, null=True)),
                ('Lat', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('Lng', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('Precipitacion', models.CharField(max_length=40)),
                ('Temp_Aire', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Alta', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Baja', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Evapotranspiracion', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Hum_Relat_Max_Temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Hum_Relat_Min_Temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Hum_Relat_Min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Hum_Relat_Max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Usuario', models.TextField(default='Arable', max_length=100, null=True)),
            ],
        ),
    ]
