# Generated by Django 4.2.1 on 2023-09-11 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clima', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Indicadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Sync', models.DateTimeField(auto_created=True, blank=True, null=True)),
                ('Date', models.DateTimeField(blank=True, null=True)),
                ('Date_Arable_Sync', models.DateTimeField(blank=True, null=True)),
                ('Lat', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('Lng', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('LocationID', models.CharField(null=True)),
                ('Device', models.CharField()),
                ('Precipitacion', models.DecimalField(decimal_places=16, max_digits=18, null=True)),
                ('Precipitacion_Hours', models.IntegerField(null=True)),
                ('Temp_Air_Mean', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Air_Min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Air_Max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Air_Max_Day', models.DateTimeField(blank=True, null=True)),
                ('Temp_Air_Min_Day', models.DateTimeField(blank=True, null=True)),
                ('Temp_Below', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Temp_Below_Mean', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Dew_Temp_Mean', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Dew_Temp_Max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Dew_Temp_At_Min_Temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Ndvi', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Evapotranspiration', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Evapotranspiration_Crop', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Relat_Hum_Mean', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Relat_Hum_Min', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Relat_Hum_Max', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Relat_Hum_Max_Temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Relat_Hum_Min_Temp', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Crop_Water_Demand', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Sunshine_Duration', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Dli', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Sea_Level_Pressure', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Vapor_Pressure', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Vapor_Pressure_Deficit', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Shortwave_Downwelling', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('Activo', models.BooleanField(default=True)),
                ('Usuario', models.TextField(default='Arable', max_length=100, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Indicadores',
        ),
    ]
