# Generated by Django 4.2.1 on 2024-02-05 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Hacienda', '0040_lote_edad'),
        ('Clima', '0002_daily_indicadores_delete_indicadores'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_indicadores',
            name='Id_Hacienda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Hacienda.hacienda'),
        ),
    ]
